apiVersion: 1

datasources:
  - name: StatusIQ Local
    uid: statusiq-local
    type: statusiq-incident-annotations-datasource
    access: proxy
    isDefault: false
    editable: true
    url: http://host.docker.internal:18080
    jsonData:
      timezone: UTC
      maxPages: 3
      encodedStatusPageId: demo-status-page-id
